"""GET /risk/nta/{nta_id}/narrative endpoint (T-27).

Returns a 2–3 sentence plain-English risk summary for one NTA,
generated by Gemini Flash grounded on:
  - Current risk score, decile, and top SHAP factors
  - Up to 5 relevant RAG chunks (policy, seasonal context, etc.)
  - 12-week TFT forecast trend (if available)

The response is cached per (nta_id, iso_week) in ``app.narrative_cache``
to avoid redundant LLM calls across requests within the same week.
Cache misses are transparent to the caller.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import date, timedelta

import asyncpg
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from rat_api.config import get_settings
from rat_api.ml.features import current_iso_week, get_nta_features
from rat_api.ml.predict import FEATURE_LABELS, predict_risk
from rat_api.rag.retrieve import retrieve

log = logging.getLogger(__name__)

router = APIRouter(prefix="/risk")

# Maximum SHAP factors to include in the LLM prompt.
_MAX_FACTORS = 3
# Maximum RAG chunks to include in the LLM prompt.
_MAX_RAG_CHUNKS = 3

_SYSTEM_PROMPT = """\
You are an expert public-health analyst specializing in urban rodent control
for New York City. Your job is to write a concise, accurate, and actionable
2–3 sentence risk summary for a specific NYC Neighborhood Tabulation Area (NTA).

Guidelines:
- Be factual and grounded in the data provided.
- Mention the most influential risk factors by their readable name.
- If risk is elevated, briefly suggest what residents or building owners can do.
- Do NOT fabricate statistics or cite sources not provided.
- Use plain English — no jargon. Avoid the word "utilize".
- Output only the summary text, no headers or bullet points.
"""


class NarrativeResponse(BaseModel):
    nta_id: str
    week: date
    narrative: str
    risk_score: float
    risk_decile: int
    rag_sources: list[str]  # citation strings from retrieved chunks


@router.get("/nta/{nta_id}/narrative", response_model=NarrativeResponse)
async def get_nta_narrative(nta_id: str, request: Request) -> NarrativeResponse:
    """Return a plain-English risk narrative for one NTA.

    Calls Gemini Flash with RAG context. Returns 503 if models are not
    loaded or if the feature row for the current week is missing.
    """
    settings = get_settings()
    model_bundle = getattr(request.app.state, "model_bundle", None)
    if model_bundle is None:
        raise HTTPException(status_code=503, detail="Models not loaded.")

    if not settings.groq_api_key:
        raise HTTPException(
            status_code=503,
            detail="GROQ_API_KEY not configured.",
        )

    week = current_iso_week()
    conn = await asyncpg.connect(settings.database_url)
    try:
        feature_row = await get_nta_features(nta_id, week, conn)

        if feature_row is None:
            raise HTTPException(
                status_code=503,
                detail=f"No feature row for nta_id={nta_id!r} week={week}.",
            )

        # Run inference to get risk score + top factors
        result = predict_risk(
            model=model_bundle["model"],
            feature_row=feature_row,
            feature_cols=model_bundle["metadata"]["feature_cols"],
            decile_thresholds=request.app.state.decile_thresholds,
            model_version=model_bundle["version"],
        )

        # Check narrative cache
        cache_key = _cache_key(nta_id, week, model_bundle["version"])
        cached = await conn.fetchrow(
            "SELECT narrative FROM app.narrative_cache WHERE cache_key = $1",
            cache_key,
        )
        if cached:
            return NarrativeResponse(
                nta_id=nta_id,
                week=week,
                narrative=cached["narrative"],
                risk_score=result.risk_score,
                risk_decile=result.risk_decile,
                rag_sources=[],
            )

        # Retrieve RAG context
        query = _build_rag_query(nta_id, result)
        try:
            chunks = await retrieve(query, conn, top_k=_MAX_RAG_CHUNKS)
        except Exception as exc:  # noqa: BLE001
            log.warning("RAG retrieval failed for %s: %s", nta_id, exc)
            chunks = []

        # Fetch optional TFT forecast
        tft_rows = await conn.fetch(
            """
            SELECT forecast_week, p50
            FROM app.tft_forecasts
            WHERE nta_id = $1 AND as_of_week = $2
            ORDER BY forecast_week
            LIMIT 12
            """,
            nta_id,
            week,
        )
    finally:
        await conn.close()

    # ── Build LLM prompt ──────────────────────────────────────────────────
    user_content = _build_user_prompt(
        nta_id=nta_id,
        week=week,
        result=result,
        tft_rows=list(tft_rows) if tft_rows else [],
        rag_chunks=chunks,
    )

    # ── Call Groq ─────────────────────────────────────────────────────────
    narrative = _call_groq(user_content, api_key=settings.groq_api_key)

    # ── Cache the result ──────────────────────────────────────────────────
    await _write_cache(cache_key, narrative, db_url=settings.database_url)

    return NarrativeResponse(
        nta_id=nta_id,
        week=week,
        narrative=narrative,
        risk_score=result.risk_score,
        risk_decile=result.risk_decile,
        rag_sources=[c.citation for c in chunks],
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _cache_key(nta_id: str, week: date, model_version: str) -> str:
    return hashlib.sha1(
        f"{nta_id}|{week.isoformat()}|{model_version}".encode()
    ).hexdigest()


def _build_rag_query(nta_id: str, result: object) -> str:  # type: ignore[type-arg]
    factors = getattr(result, "top_factors", [])[:_MAX_FACTORS]
    factor_names = ", ".join(
        FEATURE_LABELS.get(f.feature, f.feature) for f in factors
    )
    score = getattr(result, "risk_score", 0.0)
    return (
        f"NYC rat risk NTA {nta_id}: risk score {score:.2f}. "
        f"Top risk factors: {factor_names}. "
        "What are the relevant health code regulations, seasonal patterns, "
        "and mitigation actions?"
    )


def _build_user_prompt(
    *,
    nta_id: str,
    week: date,
    result: object,  # PredictionResult
    tft_rows: list,
    rag_chunks: list,
) -> str:
    risk_score = getattr(result, "risk_score", 0.0)
    risk_decile = getattr(result, "risk_decile", 1)
    top_factors = getattr(result, "top_factors", [])[:_MAX_FACTORS]

    lines = [
        f"NTA: {nta_id}",
        f"Week: {week.isoformat()}",
        f"Current risk score: {risk_score:.3f} (decile {risk_decile}/10)",
        "",
        "Top contributing factors:",
    ]
    for f in top_factors:
        direction = "increases" if f.direction == "up" else "decreases"
        label = FEATURE_LABELS.get(f.feature, f.feature)
        lines.append(f"  - {label} {direction} risk (SHAP={f.contribution:+.4f})")

    if tft_rows:
        lines += ["", "12-week forecast trend (p50 risk score):"]
        for row in tft_rows[:4]:  # show first 4 weeks
            lines.append(f"  - {row['forecast_week'].isoformat()}: {float(row['p50']):.3f}")
        if len(tft_rows) > 4:
            last = tft_rows[-1]
            lines.append(
                f"  - … → {last['forecast_week'].isoformat()}: {float(last['p50']):.3f}"
            )

    if rag_chunks:
        lines += ["", "Relevant context (from NYC policy and public health sources):"]
        for chunk in rag_chunks:
            lines.append(f"\n[{chunk.citation}]\n{chunk.content[:600]}")

    lines += [
        "",
        "Please write a 2–3 sentence risk summary for this NTA that a resident "
        "or building owner would find useful.",
    ]
    return "\n".join(lines)


def _call_groq(user_content: str, *, api_key: str) -> str:
    """Synchronous Groq call via litellm — kept thin, no streaming."""
    import litellm  # noqa: PLC0415

    response = litellm.completion(
        model="groq/llama-3.1-8b-instant",
        api_key=api_key,
        max_tokens=256,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
    )
    return response.choices[0].message.content.strip()


async def _write_cache(cache_key: str, narrative: str, *, db_url: str) -> None:
    """Best-effort cache write — ignores errors (table may not exist yet)."""
    try:
        conn = await asyncpg.connect(db_url)
        try:
            await conn.execute(
                """
                INSERT INTO app.narrative_cache (cache_key, narrative)
                VALUES ($1, $2)
                ON CONFLICT (cache_key) DO NOTHING
                """,
                cache_key,
                narrative,
            )
        finally:
            await conn.close()
    except Exception as exc:  # noqa: BLE001
        log.debug("Narrative cache write skipped: %s", exc)
